spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.183.232:3306/big_event?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 266700
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
